[env:stc89c52rc]
platform = intel_mcs51
board = STC89C52RC

; ---- 编译选项 ----
build_flags =
    -DSTC89C52RC
    --model-small
    --opt-code-size
    --stack-size 16

; ---- 上传（烧录）----
upload_protocol = stcgal
upload_speed = 57600

; ---- 串口监视器 ----
monitor_speed = 115200

; ---- clangd ----
build_type = debug